version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - "./storage:/data/db"
    ports:
      - 27017:27017

  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/todo-app

  frontend:
    container_name: frontend
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - backend
