---
- name: Provision EC2 instance with Docker
  hosts: localhost
  gather_facts: False
  
  vars_files:
    - vars/env.yaml
    - vars/generated.yaml

  tasks:
    - name: Destroy EC2 instance
      ec2_instance:
        state: absent
        region: "{{ region }}"
        instance_ids: "{{ ec2_instance_ids }}"
      when: ec2_instance_ids is defined

    - name: Delete Security Group
      ec2_group:
        state: absent
        region: "{{ region }}"
        group_id: "{{ security_group_id }}"
      when: security_group_id is defined

    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        state: absent
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
      when: vpc_id is defined

    - name: Delete Subnets
      ec2_vpc_subnet:
        state: absent
        region: "{{ region }}"
        
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.name }}"
      with_items: "{{ availability_zones }}"
      when: vpc_id is defined
        
    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        state: absent
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
      when: vpc_id is defined

    - name: Clear generated.yaml
      copy:
        content: ''
        dest: "vars/generated.yaml"
