name: Master Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set environment variables
        run: |
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Use environment variables
        run: |
          echo "GIT_BRANCH=${GIT_BRANCH}"
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get image name
        shell: bash
        run: echo "image_name=danieloleynyk/${{ github.repository }}:${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: get_image_name

      - name: Build and push Docker image
        run: |
          docker build -t danieloleynyk/devops-project:dev .
          docker push danieloleynyk/devops-project:dev

#   deploy:
#     name: Deploy to EC2
#     runs-on: ubuntu-latest

#     needs: build

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install ssh-action
#         uses: webfactory/ssh-agent@v0.5.0

#       - name: Add SSH private key
#         run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

#       - name: Connect to EC2 and redeploy docker-compose
#         uses: appleboy/ssh-action@v0.2.0
#         with:
#           host: your-ec2-ip-address
#           username: user
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /path/to/your/docker-compose/directory
#             docker-compose pull
#             docker-compose up -d
