name: Master Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get image name
        run: echo "IMAGE=${{ github.repository_owner }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}" >> $GITHUB_ENV
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${IMAGE} .
          docker push ${IMAGE}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to EC2 and redeploy docker-compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/devops-project
            docker-compose pull
            docker-compose up -d
